version: "3.7"


services:


  web1:
    build: 
          context: .
          dockerfile: Dockerfile
    image: website_php1
    container_name : app
    restart : unless-stopped
    volumes :
            -  ./:/var/www

  web2:
     build: 
          context: .
          dockerfile: Dockerfile
  image: website_php2
  container_name : app
  restart : unless-stopped
  volumes :
            -  ./:/var/www          

  nginx:
    build:
      context: ./nginx/dockerfile
      dockerfile: dockerfile
    image: nginx
    container_name : nginx_1
    restart : unless-stopped
    ports :
            - 80:80
    volumes :
            -  ./:/var/www
            - ./config/nginx/:/etc/nginx/conf.d/
    depends_on:
        - mysql
    


  mysql:
    image: mysql:8
    volumes:
      - todo-mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: todos

volumes:
  todo-mysql-data: